[project]
name = "apalis-py"
version = "0.1.0"
description = "A Python SDK for Chirpy, the language-agnostic standalone job server built on apalis."
authors = [
    { name = "Muturi Eric Wanjohi", email = "emuturi124@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anyio>=4.13.0",
]

[dependency-groups]
prod = [
    "anyio>=4.13.0",
]
dev = [
    "pytest>=9.0.3",
    "pytest-timeout>=2.4.0",
    "python-dotenv>=1.2.2",
]
